### PR TITLE
Switch standard to eslint (with standard config)

### PR DESCRIPTION
**Pull request by fgblomqvist**
Rather than using `standard`, using `eslint` with the `standard` config gives better future flexibility and tighter IDE integration (due to the excellent OOB suipport for eslint in most editors).

### CODE REVIEW

**Comment by auggod** [comment]
Do I need to change anything about my vim config? Currently using standard with ALE.

**Comment by fgblomqvist** [comment]
@auggod yes you will have to switch to eslint in ALE (they support that), so shouldn't be a big change 🙂

**Comment by auggod** [comment]
I can merge once the conflicts have been resolved!

**Comment by auggod** [comment]
Ok, i think we'll have to do this for all our javascripts projects otherwise I'll have to add project specific vimrc's

**Comment by fgblomqvist** [comment]
While I can only be in favor of giving the other projects the same treatment, having separate vimrc's per project doesn't sound too bad in the meantime? I'm not a vim user though so I am not entirely sure what that entails. Ultimately, though, it's inevitable that different projects have different setups (like what about your other projects that aren't resonate?). There's gotta be an easy way to use different linters/code checkers for different projects? :thinking:

**Comment by auggod** [comment]
Yes, using a project specific vimrc should override previous rules. I can add documentation on this.

**Pull request merged**
