### PR TITLE
 Make removing tracks from playlists more intuitive

### LINKED ISSUE #134: Make removing tracks from playlists more intuitive
### Operating system
macOS 11.6.2

### Browser name and version
Firefox 95.02

### Expected behavior
Should be obvious to the user how to remove tracks from playlists.

### Actual behavior
It is not obvious to the user how to remove tracks from playlists.

### Steps to reproduce behavior
Create a new playlist, add a few songs, go to your playlist. Click the three dots menu on the right side of a song, there is no available `Remove from playlist` option, only `Add to playlist`, implying that the function only performs additions and not removals. Perhaps `Add/Remove from playlist` or `Modify playlist representation` would be more suitable. I only realized you could uncheck the box to remove from playlist after digging through the code and finding the if/else block that depended on `checked`.

### PR DESCRIPTION
**Pull request by peterklingelhofer**
Inform user in the `Add to playlist` modal window that they can also use the modal to remove tracks from playlist whatever playlists they so choose.

I tried changing the menu item itself from `Add to playlist` to `Add to/remove from playlist`, but it makes the menu item's text wrap to the next line, making the menu item twice as tall as all of the other menu items, so I left that side of things alone.

Screen Shot 2022-01-16 at 10 11 22 PM

Perhaps changing the menu item's icon from a plus to a plus/minus (±) would also provide more clarity to the user:
Screen Shot 2022-01-22 at 11 30 32 AM

This closes #134.

### CODE REVIEW

**Comment by hakanto** [comment]
Love the idea of using a plus/minus icon.

Not sure if it would be sufficiently intuitive, but perhaps the combination of a plus/minus symbol and simply the word "Playlists" on the menu would get the point across.

**Comment by hakanto** [comment]
For the modal, I'd suggest the header text  "Add or remove from playlists".
- "add or remove" is more literal and less open to misinterpretation
- "playlists" since you can add or remove the track from all your playlists, not just one

**Comment by peterklingelhofer** [comment]
> For the modal, I'd suggest the header text "Add or remove from playlists".
> 
>     * "add or remove" is more literal and less open to misinterpretation
> 
>     * "playlists" since you can add or remove the track from all your playlists, not just one

Great idea. I've updated the header with your wording suggestion and the screenshot to match.

**Comment by peterklingelhofer** [comment]
> Love the idea of using a plus/minus icon.
> 
> Not sure if it would be sufficiently intuitive, but perhaps the combination of a plus/minus symbol and simply the word "Playlists" on the menu would get the point across.

Here's how it looks with just "Playlist". I like it in that we're no longer potentially making the user think that they can only add a track to a playlist. Downside to this is they might think this has to do with creating or deleting their own playlists and doesn't pertain to this specific track's representation in said playlists. What do you think, @hakanto?

Screen Shot 2022-01-16 at 10 16 36 PM

**Comment by hakanto** [comment]
Sorry for the late reply. Using "Playlists" in the three dot menu is more clear than "Playlist". Doesn't solve all the potential confusion, but minimizes it. I'd suggest using "Playlists" and then merging. We can always improve it again later! This is a great step forward :clap:

**Comment by peterklingelhofer** [comment]
> Sorry for the late reply. Using "Playlists" in the three dot menu is more clear than "Playlist". Doesn't solve all the potential confusion, but minimizes it. I'd suggest using "Playlists" and then merging. We can always improve it again later! This is a great step forward 👏

I think the plural "Playlists" suggestion makes way more sense (I realize I accidentally used the singular which isn't what you had suggesting above). I've updated the screenshot in this pull request's description to reflect the latest changes, I think it's looking good! Code changes visible here: https://github.com/resonatecoop/stream/pull/135/commits/4472cdf98f3d0c08dd3468f776847e43dd3c054d.

**Pull request merged**
