### PR TITLE
[for discussion only] Release Filters working Locally

### PR DESCRIPTION
**Pull request by whatSocks**
on https://beta.stream.resonate.coop, I can see the filters working - the URL updates, and the filters filter. 

Screen Shot 2021-09-05 at 12 09 09 PM

Locally, I can't get that to happen with the code as it is, perhaps I have something configured wrong? Below is what I have to do to get the filters working locally.

### CODE REVIEW

**Comment by auggod** [comment]
It's a bit redundant but the .env file should have both APP_DOMAIN and APP_HOST configured. It was missing https://beta.stream.resonate.tld as APP_HOST.
The reason the filters were not working is that the URL would end up invalid.
I can't merge your code because it won't trigger a navigation change and update the query parameters anymore.

I have pushed the missing .env key APP_HOST to the .env.example. We should have been using dotenv-safe (npm module) to catch missing .env values.

**Comment by whatSocks** [comment]
great I'll try this version 
update: filters don't work locally. 

error: `Uncaught DOMException: The operation is insecure.` 

Screen Shot 2021-09-06 at 10 37 25 AM

Here is my env file:

```[api]
API_DOMAIN=api.resonate.coop
APP_DOMAIN=beta.stream.resonate.coop
APP_HOST=https://beta.stream.resonate.tld
APP_ENV=development
COOKIE_DOMAIN=.resonate.coop
SITE_DOMAIN=resonate.coop
STRIPE_TOKEN=pk_***
DISABLE_NANOTIMING=no
LOG_LEVEL=debug
RATES_API_HOST=https://api.ratesapi.io
PACKAGE_URL=https://raw.githubusercontent.com/resonatecoop/resonate/develop/beta/package.json
SW_VERSION=version2
```

**Comment by auggod** [comment]
Careful here, you may use http://localhost:8080 for APP_HOST, it was just an example with .tld at the end.

I'm not sure why it's complaining with 'insecure' though.

It's recommended to serve the app on https as it's a PWA and PWA's only works with https. For that you will need nginx + a self signed certificate of your choice.

See https://github.com/FiloSottile/mkcert

There's an example nginx.conf template here: https://github.com/resonatecoop/stream/blob/7.x-dev-release/nginx.conf

You may change https://github.com/resonatecoop/stream/blob/7.x-dev-release/nginx.conf#L69 into ```proxy_pass http://localhost:8080;```

When you are done configuring nginx and ssl. Don't forget to update your env variables. You can register a certificate for localhost or beta.stream.resonate.localhost, the latter is what i use.

**Comment by whatSocks** [comment]
> Careful here, you may use http://localhost:8080 for APP_HOST, it was just an example with .tld at the end.

aha, so changing this allowed me to use the filters on the release page. Strangely, I still can't change the order on the tracks list. 

I'll configure nginx and ssl and see what happens

**Comment by whatSocks** [comment]
is this a better example configuration? In the one you linked I don't see a way to point to the cert 

https://github.com/resonatecoop/stream/blob/develop/docs/nginx/beta.resonate.localhost.conf

**Comment by whatSocks** [comment]
at this point I'm afraid to mess up my environment by accident :( 

* nginx is OK
* hosts file updated
* tried using default env vars / my best guess env vars
* certificate generated
* tried both versions of nginx.conf file (the one you linked here and in the docs)

filters still no work

**Comment by auggod** [comment]
In nginx, you can add `add_header Service-Worker-Allowed /;` it may fix this firefox problem.

**Comment by whatSocks** [comment]
> In nginx, you can add `add_header Service-Worker-Allowed /;` it may fix this firefox problem.

sure, if I could get past the "Welcome to nginx!" page :p 


Should I be using one of the provided nginx.conf templates? If so, which one?

**Comment by auggod** [comment]
You can ignore the nginx example in the docs for now. Just make sure to listen also to 443 and add certificates. The nginx example assumes you do know how to configure ssl.

**Comment by whatSocks** [comment]
omg it was because I missed the b this whole time. 

```
This server could not prove that it is beta.resonate.localhost; its security certificate is from eta.resonate.localhost. This may be caused by a misconfiguration or an attacker intercepting your connection.
```

**Comment by whatSocks** [comment]
Alright, check out the secure connection (testing on `7.x-dev-release`):

Screen Shot 2021-09-07 at 11 07 16 PM

interacting with the filters (tapped LP):

Screen Shot 2021-09-07 at 11 11 02 PM

**Comment by auggod** [comment]
Cool! You can switch to 'development' branch now. I'm going to drop '7.x***' at some point.

I also think this is not the right place for a continued discussion. Would you like to chat on telegram? You can send me a PM on the community forums.

I'm going to close this for now.

**Pull request closed without merging**
