### PR TITLE
update: users to add / edit the tags on their playlists, view public playlists

### PR DESCRIPTION
**Pull request by whatSocks**
[comment out of date]

### CODE REVIEW

**Comment by whatSocks** [comment]
blocked until https://github.com/resonatecoop/stream/issues/104 is fixed

detail view
Screen Shot 2021-09-03 at 9 31 52 PM

edit view
image

list view
Screen Shot 2021-09-12 at 11 27 20 AM

**Comment by whatSocks** [comment]
Pic of page as a whole

Screen Shot 2021-09-03 at 8 43 27 PM

**Comment by auggod** [comment]
Great feature suggestion here! It would be best to adapt your code to match changes in #96 so we don't have problems merging in the future. We're no longer using lib/api.js for our v2 api.

**Comment by auggod** [comment]
Wait, I decided to rename branch associated to #96, working on improving our workflow.

**Comment by auggod** [comment]
See new pull request #100 for new-website-release branch.

**Comment by hakanto** [comment]
Love this! Let's do it

**Pull request merged**
