### PR TITLE
Convert first half of the views to TS

### PR DESCRIPTION
**Pull request by fgblomqvist**
Converts the first half of the views to TS.

Some notes:
* Used arrow functions to be able to type the function as a whole. As in, the args will be correctly typed automatically (i.e. the `state` and `emit` args).
* Improved some types so that we can correctly type `state.cache` calls to ensure that the correct props are passed to the referenced component (once the components are typed).
* I don't think the factory pattern is needed when exporting the view. Each view can just directly export their layout-wrapped view. However, it's easier to change this once all views have been converted.

As with the other PR, the GH diff view is pretty useless. There are very few modifications in each converted file (mostly just imports + exports + function def).

### CODE REVIEW

**Comment by fgblomqvist** [comment]
#194 needs to be merged before this one.

**Comment by fgblomqvist** [comment]
@auggod lmk if there's any way I can make this PR easier to review. For example, if you prefer to get smaller PRs for these conversions that is certainly doable.

**Comment by peterklingelhofer** [comment]
I did some testing on these changes, I wasn't able to break anything clicking around the player and performing actions. Behaves same as the development branch for me. Not seeing any type errors.

**Comment by peterklingelhofer** [comment]
Noticed a difference between this PR and the up-to-date `development` branch this evening.

I get [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPViolation) error twice in Firefox. (Chrome seems to be the same though...)
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:71:797943
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:71:797943
```

It may be the same [problem](https://github.com/resonatecoop/stream/pull/220#pullrequestreview-926914923) I had on the other TypeScript MR where the branch needed to be updated from `upstream development`. I tried locally but ran into merge conflicts and didn't proceed further. Not sure if this error is significant or not either. Any ideas, @fgblomqvist?

**Comment by fgblomqvist** [comment]
Yeah that bug used to exist on develop but I guess it was fixed. Will merge in latest later today.

**Pull request closed without merging**
