### PR TITLE
Migrate to workspaces

### LINKED ISSUE #76: Migrate from lerna to npm 7 workspaces
Determine if migrating from lerna to npm 7 worspaces is a good idea. This will require some more experimentation on my end.

### PR DESCRIPTION
**Pull request by fgblomqvist**
Closes #76.

I'm not entirely sure about all parts of this, but I'm gonna try to test as much as possible to make sure that things still work in the same/similar fashion as before.

The one lost feature I have seen so far is the `lerna publish` command, which does not have an equivalent one in npm workspaces. I'm not sure how widely used that command is, but if it is indeed used then it can most likely be replaced with a different dep.

The benefit of switching to npm workspaces is that the learning curve for working on the project goes down since most people are familiar with `npm` but not necessarily with `lerna`. Overall I would say the complexity goes down as well.

Open discuss any/all of the changes!

### CODE REVIEW

**Comment by auggod** [comment]
In the end, we only use a few features from lerna. As for publishing single packages, I always did with npm directly.
I also suppose using workspaces make it easier to run npm audits.

**Comment by fgblomqvist** [comment]
Ah nice. Yeah it should certainly simplify some workflows like that. Merged in the latest changes so that the CI should pass. Though I'll take a last pass tonight to ensure that the lerna publish script is gone and that things are in order, then it should be good to go.

**Comment by auggod** [comment]
If we remove .npmrc, we can create a root package-lock and run npm audits properly. Anyway, it's only warnings about postcss and other dev tools

**Comment by auggod** [comment]
I have no objections to merge when you are ready

**Comment by fgblomqvist** [comment]
> If we remove .npmrc, we can create a root package-lock and run npm audits properly. Anyway, it's only warnings about postcss and other dev tools

Sounds good, could be a good task for another PR.

> I have no objections to merge when you are ready

Should be ready to roll now :rocket:

**Pull request merged**
